export const USER_LITSV3_SUCCESS = "USER_LITSV3_SUCCESS";
export const USER_LITSV3_FAIL = "USER_LITSV3_FAIL";
export const USER_LITSV3_LOADMORE = "USER_LITSV3_LOADMORE";
export const USER_LITSV3_SCROLL = "USER_LITSV3_SCROLL";

